In [123]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import QuantileTransformer
from sklearn.decomposition import PCA
import pickle

In [124]:
with open('cluster.pkl', 'rb') as f:
    cluster_model = pickle.load(f)
cluster_model

RandomForestClassifier(random_state=42)

In [125]:
test_df = pd.read_csv('test_data.csv')
test_df.columns = test_df.columns.str.strip()
test_df

,Index,ROA(C) before interest and depreciation before interest,ROA(A) before interest and % after tax,ROA(B) before interest and depreciation after tax,Operating Gross Margin,Realized Sales Gross Margin,Operating Profit Rate,Pre-tax net Interest Rate,After-tax net Interest Rate,Non-industry income and expenditure/revenue,...,Net Income to Total Assets,Total assets to GNP price,No-credit Interval,Gross Profit to Sales,Net Income to Stockholder's Equity,Liability to Equity,Degree of Financial Leverage (DFL),Interest Coverage Ratio (Interest expense to EBIT),Net Income Flag,Equity to Liability
0,0,0.414323,0.481029,0.468280,0.609514,0.609514,0.998889,0.797159,0.809132,0.303290,...,0.761704,0.001404,0.623973,0.609512,0.838286,0.275450,0.026749,0.564950,1,0.136203
1,1,0.497441,0.560892,0.546603,0.610660,0.610660,0.999108,0.797545,0.809431,0.303506,...,0.815244,0.004466,0.623724,0.610658,0.842427,0.285886,0.026965,0.565870,1,0.018871
2,2,0.501584,0.548899,0.556721,0.606134,0.606134,0.999034,0.797427,0.809370,0.303453,...,0.806318,0.000684,0.625387,0.606132,0.840598,0.275816,0.026793,0.565165,1,0.095511
3,3,0.574465,0.637375,0.619680,0.600376,0.600376,0.999030,0.797528,0.809426,0.303640,...,0.852655,0.001718,0.624151,0.600375,0.844727,0.279977,0.026795,0.565178,1,0.028513
4,4,0.393360,0.456444,0.440334,0.600009,0.600009,0.998800,0.797025,0.809000,0.303240,...,0.741604,0.002545,0.623612,0.600009,0.835578,0.279901,0.026623,0.564204,1,0.028779
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1007,1007,0.495783,0.569178,0.542749,0.597630,0.597630,0.998992,0.797416,0.809336,0.303523,...,0.809437,0.002755,0.623668,0.597631,0.841922,0.288167,0.027252,0.566689,1,0.017410
1008,1008,0.556038,0.532054,0.591306,0.607597,0.607597,0.998986,0.797375,0.809302,0.303464,...,0.795545,0.008081,0.623772,0.607594,0.840017,0.276395,0.022035,0.571637,1,0.066725
1009,1009,0.580705,0.586731,0.624284,0.608938,0.608938,0.999143,0.797555,0.809461,0.303450,...,0.827790,0.002488,0.623751,0.608939,0.842411,0.278794,0.026850,0.565423,1,0.033767
1010,1010,0.459465,0.538378,0.520959,0.601818,0.601818,0.998984,0.797376,0.809316,0.303471,...,0.800113,0.000452,0.624152,0.601819,0.840305,0.277226,0.026769,0.565052,1,0.048269
1011,1011,0.502608,0.554568,0.552439,0.610271,0.610271,0.999017,0.797444,0.809366,0.303518,...,0.809193,0.000769,0.623814,0.610272,0.841005,0.278561,0.026861,0.565473,1,0.035182

In [126]:
index = test_df['Index']
X = test_df.drop('Index', axis=1)
X

,ROA(C) before interest and depreciation before interest,ROA(A) before interest and % after tax,ROA(B) before interest and depreciation after tax,Operating Gross Margin,Realized Sales Gross Margin,Operating Profit Rate,Pre-tax net Interest Rate,After-tax net Interest Rate,Non-industry income and expenditure/revenue,Continuous interest rate (after tax),...,Net Income to Total Assets,Total assets to GNP price,No-credit Interval,Gross Profit to Sales,Net Income to Stockholder's Equity,Liability to Equity,Degree of Financial Leverage (DFL),Interest Coverage Ratio (Interest expense to EBIT),Net Income Flag,Equity to Liability
0,0.414323,0.481029,0.468280,0.609514,0.609514,0.998889,0.797159,0.809132,0.303290,0.781361,...,0.761704,0.001404,0.623973,0.609512,0.838286,0.275450,0.026749,0.564950,1,0.136203
1,0.497441,0.560892,0.546603,0.610660,0.610660,0.999108,0.797545,0.809431,0.303506,0.781691,...,0.815244,0.004466,0.623724,0.610658,0.842427,0.285886,0.026965,0.565870,1,0.018871
2,0.501584,0.548899,0.556721,0.606134,0.606134,0.999034,0.797427,0.809370,0.303453,0.781657,...,0.806318,0.000684,0.625387,0.606132,0.840598,0.275816,0.026793,0.565165,1,0.095511
3,0.574465,0.637375,0.619680,0.600376,0.600376,0.999030,0.797528,0.809426,0.303640,0.781691,...,0.852655,0.001718,0.624151,0.600375,0.844727,0.279977,0.026795,0.565178,1,0.028513
4,0.393360,0.456444,0.440334,0.600009,0.600009,0.998800,0.797025,0.809000,0.303240,0.781206,...,0.741604,0.002545,0.623612,0.600009,0.835578,0.279901,0.026623,0.564204,1,0.028779
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1007,0.495783,0.569178,0.542749,0.597630,0.597630,0.998992,0.797416,0.809336,0.303523,0.781585,...,0.809437,0.002755,0.623668,0.597631,0.841922,0.288167,0.027252,0.566689,1,0.017410
1008,0.556038,0.532054,0.591306,0.607597,0.607597,0.998986,0.797375,0.809302,0.303464,0.781563,...,0.795545,0.008081,0.623772,0.607594,0.840017,0.276395,0.022035,0.571637,1,0.066725
1009,0.580705,0.586731,0.624284,0.608938,0.608938,0.999143,0.797555,0.809461,0.303450,0.781756,...,0.827790,0.002488,0.623751,0.608939,0.842411,0.278794,0.026850,0.565423,1,0.033767
1010,0.459465,0.538378,0.520959,0.601818,0.601818,0.998984,0.797376,0.809316,0.303471,0.781571,...,0.800113,0.000452,0.624152,0.601819,0.840305,0.277226,0.026769,0.565052,1,0.048269
1011,0.502608,0.554568,0.552439,0.610271,0.610271,0.999017,0.797444,0.809366,0.303518,0.781625,...,0.809193,0.000769,0.623814,0.610272,0.841005,0.278561,0.026861,0.565473,1,0.035182

In [127]:
#Got cols associated with transformation from 3.1
with open('cluster_features.pkl', 'rb') as f:
    cluster_cols = pickle.load(f)

X_cluster = X[cluster_cols]
X_cluster

,ROA(C) before interest and depreciation before interest,Operating Gross Margin,Cash flow rate,Net Value Per Share (B),Cash Flow Per Share,Debt ratio %,Fixed Assets Turnover Frequency,Operating profit per person,Working Capital to Total Assets,Cash/Total Assets,Cash/Current Liability,Total expense/Assets,Cash Flow to Total Assets
0,0.414323,0.609514,0.455909,0.172138,0.316227,0.027058,3.184860e-04,0.389057,0.930352,0.107350,0.020316,0.064586,0.651225
1,0.497441,0.610660,0.476061,0.158443,0.323937,0.185688,8.700000e+08,0.407668,0.751470,0.014078,0.002475,0.018125,0.627060
2,0.501584,0.606134,0.470906,0.161519,0.320259,0.039877,2.867130e-04,0.393003,0.860618,0.283278,0.036192,0.024155,0.643327
3,0.574465,0.600376,0.469399,0.208124,0.329313,0.130030,2.627317e-03,0.413435,0.823212,0.074313,0.006515,0.017971,0.670377
4,0.393360,0.600009,0.460686,0.174287,0.316474,0.128942,1.301180e-04,0.374709,0.746007,0.030559,0.001531,0.052140,0.647619
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1007,0.495783,0.597630,0.459908,0.191606,0.309118,0.198446,2.045570e-03,0.403406,0.807640,0.118288,0.003654,0.017771,0.664079
1008,0.556038,0.607597,0.477903,0.174666,0.327191,0.057805,4.840000e+09,0.392653,0.746774,0.030648,0.002780,0.014897,0.641158
1009,0.580705,0.608938,0.473300,0.177110,0.329702,0.111528,1.286050e-04,0.397470,0.791051,0.024898,0.001765,0.019829,0.639168
1010,0.459465,0.601818,0.471349,0.195146,0.331435,0.079602,1.759538e-02,0.397074,0.898224,0.367721,0.022756,0.048817,0.794776
1011,0.502608,0.610271,0.467408,0.183979,0.325706,0.107386,1.596210e-04,0.393071,0.799520,0.020855,0.001230,0.036953,0.613067

In [128]:
cluster_ids = cluster_model.predict(X_cluster)
X['Cluster'] = cluster_ids
X.groupby('Cluster').size()

Cluster
3     22
4    990
dtype: int64

# Cluster 2

In [129]:
def predict_cluster2(df_new):
    with open("models/cluster2_model.pkl", "rb") as f:
        model = pickle.load(f)
    with open("models/cluster2_threshold.pkl", "rb") as f:
        thr = pickle.load(f)
    with open("models/cluster2_features.pkl", "rb") as f:
        cols = pickle.load(f)
    X_new = df_new[cols].values
    probs = model.predict_proba(X_new)[:, 1]
    return (probs >= thr).astype(int)

# Cluster #4

In [130]:
with open('group4processing.pkl', 'rb') as f:
    loaded_data = pickle.load(f)
loaded_data

{'selector': SelectKBest(),
 'normal1': QuantileTransformer(output_distribution='normal', random_state=42),
 'pca': PCA(n_components=5, random_state=42),
 'normal2': QuantileTransformer(output_distribution='normal', random_state=42),
 'subgroup_model': StackingClassifier(cv=5,
                    estimators=[('knn', KNeighborsClassifier()),
                                ('svc',
                                 SVC(C=1, class_weight='balanced',
                                     random_state=42)),
                                ('dt',
                                 DecisionTreeClassifier(class_weight='balanced',
                                                        random_state=42)),
                                ('et',
                                 ExtraTreesClassifier(class_weight='balanced',
                                                      n_estimators=200,
                                                      random_state=42)),
                                ('rf',
                                 RandomForestClassifier(class_weight='balanced',
                                                        random_state=42))],
                    final_estimator=LogisticRegression(class_weight='balanced',
                                                       max_iter=2000,
                                                       random_state=42))}

In [131]:
df4 = X[X['Cluster'] == 4]
df4

,ROA(C) before interest and depreciation before interest,ROA(A) before interest and % after tax,ROA(B) before interest and depreciation after tax,Operating Gross Margin,Realized Sales Gross Margin,Operating Profit Rate,Pre-tax net Interest Rate,After-tax net Interest Rate,Non-industry income and expenditure/revenue,Continuous interest rate (after tax),...,Total assets to GNP price,No-credit Interval,Gross Profit to Sales,Net Income to Stockholder's Equity,Liability to Equity,Degree of Financial Leverage (DFL),Interest Coverage Ratio (Interest expense to EBIT),Net Income Flag,Equity to Liability,Cluster
0,0.414323,0.481029,0.468280,0.609514,0.609514,0.998889,0.797159,0.809132,0.303290,0.781361,...,0.001404,0.623973,0.609512,0.838286,0.275450,0.026749,0.564950,1,0.136203,4
1,0.497441,0.560892,0.546603,0.610660,0.610660,0.999108,0.797545,0.809431,0.303506,0.781691,...,0.004466,0.623724,0.610658,0.842427,0.285886,0.026965,0.565870,1,0.018871,4
2,0.501584,0.548899,0.556721,0.606134,0.606134,0.999034,0.797427,0.809370,0.303453,0.781657,...,0.000684,0.625387,0.606132,0.840598,0.275816,0.026793,0.565165,1,0.095511,4
3,0.574465,0.637375,0.619680,0.600376,0.600376,0.999030,0.797528,0.809426,0.303640,0.781691,...,0.001718,0.624151,0.600375,0.844727,0.279977,0.026795,0.565178,1,0.028513,4
4,0.393360,0.456444,0.440334,0.600009,0.600009,0.998800,0.797025,0.809000,0.303240,0.781206,...,0.002545,0.623612,0.600009,0.835578,0.279901,0.026623,0.564204,1,0.028779,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1007,0.495783,0.569178,0.542749,0.597630,0.597630,0.998992,0.797416,0.809336,0.303523,0.781585,...,0.002755,0.623668,0.597631,0.841922,0.288167,0.027252,0.566689,1,0.017410,4
1008,0.556038,0.532054,0.591306,0.607597,0.607597,0.998986,0.797375,0.809302,0.303464,0.781563,...,0.008081,0.623772,0.607594,0.840017,0.276395,0.022035,0.571637,1,0.066725,4
1009,0.580705,0.586731,0.624284,0.608938,0.608938,0.999143,0.797555,0.809461,0.303450,0.781756,...,0.002488,0.623751,0.608939,0.842411,0.278794,0.026850,0.565423,1,0.033767,4
1010,0.459465,0.538378,0.520959,0.601818,0.601818,0.998984,0.797376,0.809316,0.303471,0.781571,...,0.000452,0.624152,0.601819,0.840305,0.277226,0.026769,0.565052,1,0.048269,4
1011,0.502608,0.554568,0.552439,0.610271,0.610271,0.999017,0.797444,0.809366,0.303518,0.781625,...,0.000769,0.623814,0.610272,0.841005,0.278561,0.026861,0.565473,1,0.035182,4

In [132]:
def preprocess_group4(X):
    X = X.drop(['Net Income Flag', 'Liability-Assets Flag', 'Cluster'], axis=1)
    data = loaded_data['selector'].transform(X)
    selected_features = X.columns[loaded_data['selector'].get_support()].tolist()
    df = pd.DataFrame(data, columns=selected_features)

    data1 = loaded_data['normal1'].transform(df)
    df1 = pd.DataFrame(data1, columns=selected_features)

    data2 = loaded_data['pca'].transform(df1)
    pc_df = pd.DataFrame(data2, columns=[f'Feature Number {i+1}' for i in range(data2.shape[1])])

    data3 = loaded_data['normal2'].transform(pc_df)
    pc_df = pd.DataFrame(data3, columns=pc_df.columns)
    return pc_df

processed_data = preprocess_group4(df4)
processed_data

,Feature Number 1,Feature Number 2,Feature Number 3,Feature Number 4,Feature Number 5
0,-1.047534,-2.892768,0.293539,-1.488762,0.892272
1,1.828088,0.658849,0.241360,-0.514276,-0.205131
2,-1.873695,-1.798721,-1.572661,0.940625,2.384886
3,-0.399154,2.119259,0.369360,-1.054781,0.622185
4,1.322941,-2.373273,-0.750276,0.041459,-0.620205
...,...,...,...,...,...
985,1.979874,0.842133,-0.815000,-0.054455,0.746231
986,0.364945,-1.603744,0.707377,2.634574,0.076336
987,-0.055617,0.682028,0.162458,0.690803,-0.685961
988,-1.561593,-1.679474,-2.173480,-0.284806,1.997715
989,-0.166518,-0.260433,-0.823304,-0.452006,-1.580681

In [133]:
def predict4(X):
    processed_data = preprocess_group4(X)
    return loaded_data['subgroup_model'].predict(processed_data)

In [134]:
print(predict4(df4))

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

# Cluster 1

In [135]:
import joblib
with open('stacking_model.pkl', 'rb') as f:
    model = joblib.load(f)
model

with open('scaler.pkl', 'rb') as f:
    scaler = joblib.load(f)
scaler
with open('features.pkl', 'rb') as f:
    selected_features = joblib.load(f)
selected_features

['Operating profit per person',
 'ROA(C) before interest and depreciation before interest',
 'Net Value Per Share (B)',
 'Working Capital to Total Assets']

In [136]:
cluster1_test_df = X[X['Cluster'] == 1].copy()
cluster1_test_df

Empty DataFrame
Columns: [ROA(C) before interest and depreciation before interest, ROA(A) before interest and % after tax, ROA(B) before interest and depreciation after tax, Operating Gross Margin, Realized Sales Gross Margin, Operating Profit Rate, Pre-tax net Interest Rate, After-tax net Interest Rate, Non-industry income and expenditure/revenue, Continuous interest rate (after tax), Operating Expense Rate, Research and development expense rate, Cash flow rate, Interest-bearing debt interest rate, Tax rate (A), Net Value Per Share (B), Net Value Per Share (A), Net Value Per Share (C), Persistent EPS in the Last Four Seasons, Cash Flow Per Share, Revenue Per Share (Yuan ¥), Operating Profit Per Share (Yuan ¥), Per Share Net profit before tax (Yuan ¥), Realized Sales Gross Profit Growth Rate, Operating Profit Growth Rate, After-tax Net Profit Growth Rate, Regular Net Profit Growth Rate, Continuous Net Profit Growth Rate, Total Asset Growth Rate, Net Value Growth Rate, Total Asset Return Growth Rate Ratio, Cash Reinvestment %, Current Ratio, Quick Ratio, Interest Expense Ratio, Total debt/Total net worth, Debt ratio %, Net worth/Assets, Long-term fund suitability ratio (A), Borrowing dependency, Contingent liabilities/Net worth, Operating profit/Paid-in capital, Net profit before tax/Paid-in capital, Inventory and accounts receivable/Net value, Total Asset Turnover, Accounts Receivable Turnover, Average Collection Days, Inventory Turnover Rate (times), Fixed Assets Turnover Frequency, Net Worth Turnover Rate (times), Revenue per person, Operating profit per person, Allocation rate per person, Working Capital to Total Assets, Quick Assets/Total Assets, Current Assets/Total Assets, Cash/Total Assets, Quick Assets/Current Liability, Cash/Current Liability, Current Liability to Assets, Operating Funds to Liability, Inventory/Working Capital, Inventory/Current Liability, Current Liabilities/Liability, Working Capital/Equity, Current Liabilities/Equity, Long-term Liability to Current Assets, Retained Earnings to Total Assets, Total income/Total expense, Total expense/Assets, Current Asset Turnover Rate, Quick Asset Turnover Rate, Working capitcal Turnover Rate, Cash Turnover Rate, Cash Flow to Sales, Fixed Assets to Assets, Current Liability to Liability, Current Liability to Equity, Equity to Long-term Liability, Cash Flow to Total Assets, Cash Flow to Liability, CFO to Assets, Cash Flow to Equity, Current Liability to Current Assets, Liability-Assets Flag, Net Income to Total Assets, Total assets to GNP price, No-credit Interval, Gross Profit to Sales, Net Income to Stockholder's Equity, Liability to Equity, Degree of Financial Leverage (DFL), Interest Coverage Ratio (Interest expense to EBIT), Net Income Flag, Equity to Liability, Cluster]
Index: []

[0 rows x 96 columns]

In [137]:
def predict_my_subgroup(X):
    X_selected = X[selected_features]
    X_scaled = scaler.transform(X_selected)  # no .to_numpy() needed
    return model.predict(X_scaled)

In [138]:
'''preds = predict_my_subgroup(cluster1_test_df)
print("First few predictions for Cluster 1:", preds)
print("Total number of predictions for Cluster 1:", len(preds))'''

'preds = predict_my_subgroup(cluster1_test_df)\nprint("First few predictions for Cluster 1:", preds)\nprint("Total number of predictions for Cluster 1:", len(preds))'

# Cluster 0

In [139]:
with open('subgroup_0_model.pkl', 'rb') as f:
    pipeline = pickle.load(f)
pipeline.steps

df_0 = X[X['Cluster'] == 0]
def process_subgroup0(pipeline, df):
    df1 = df.drop('Cluster', axis=1)
    scaler = pipeline.named_steps['scale']
    selector = pipeline.named_steps['select']
    df0_scaled = scaler.transform(df1)
    df0_reduced = selector.transform(df0_scaled)
    return df0_reduced

def predict0(pipeline, df, stacking_model):
    X = process_subgroup0(pipeline, df)
    predictions = stacking_model.predict(X)
    print("count 0:", np.sum(predictions==0))
    print("count 1:", np.sum(predictions==1))
    return predictions

In [140]:
bankrupt = []
for idx in X.index:
    row = X.loc[[idx]] 
    cl = row['Cluster'].iat[0]
    if cl == 0:
        bankrupt.append(predict0(pipeline, row, pipeline.named_steps['model']))
        #print(predict0(pipeline, row, pipeline.named_steps['model']))
    elif cl == 1:
        bankrupt.append(predict_my_subgroup(row)[0])
        #print(predict_my_subgroup(row)[0])
    elif cl == 2:
        bankrupt.append(predict_cluster2(row)[0])
    elif cl == 3:
        bankrupt.append(0)
    elif cl == 4:
        bankrupt.append(predict4(row)[0])
        

answer = pd.DataFrame({
    'Index': index,
    'Bankrupt?': bankrupt
})
answer

      Index  Bankrupt?
0         0          0
1         1          0
2         2          0
3         3          0
4         4          0
...     ...        ...
1007   1007          0
1008   1008          0
1009   1009          0
1010   1010          0
1011   1011          0

[1012 rows x 2 columns]

In [141]:
print(answer['Bankrupt?'].value_counts())

Bankrupt?
0    992
1     20
Name: count, dtype: int64

In [142]:
print(answer['Bankrupt?'].value_counts()/len(answer))

Bankrupt?
0    0.980237
1    0.019763
Name: count, dtype: float64

In [143]:
answer.to_csv('GroupNumber_Generalization.csv', index=False)